### ISSUE TITLE
Download problem

### ISSUE THREAD

**Issue by SanderWxD** [turicfr/nick-downloader#3]
When I try to download any episode, I get the following error messages right after selecting the episode number:

Which episode? 1
Traceback (most recent call last):
  File "C:\Users\Sander\Desktop\nick_eu.py", line 122, in <module>
    main()
  File "C:\Users\Sander\Desktop\nick_eu.py", line 119, in main
    episode.download()
  File "C:\Users\Sander\Desktop\nick_eu.py", line 59, in download
    self._download_item(url, os.path.join(dirname, title))
  File "C:\Users\Sander\Desktop\nick_eu.py", line 34, in _download_item
    ffmpeg.input(src).output(f"{output}.mp4", vcodec="copy").overwrite_output().run()
  File "E:\Programma's\Python\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "E:\Programma's\Python\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "E:\Programma's\Python\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\Programma's\Python\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Het systeem kan het opgegeven bestand niet vinden

The last line translates to: "The system cannot find the specified file".
https://pastebin.com/DuYYC8pT

It will create a folder with the showname and a subfolder with the episode name but the that folder is empty.

Another minor problem:
The show "Avatar: De legende van Aang" [Avatar: The last Airbender in English] Contains a ":" which is a character that cannot be used in folder file names, thus won't work (console will just close).

Changing line 37 in nick_eu.py from
"        dirname = os.path.join(self.series.name, format_name(self.name))"
to
"        dirname = os.path.join(self.series.name.replace(":", "-"), format_name(self.name).replace(":", "-"))" 
Fixes that issue but the first issue still occurs.

I experience it with every episode (In Dutch) that I tried to download.

I'm not familiar with python or coding in general so pardon me for any stupid comments.

**Comment by turicfr** [comment]
Thank you for reporting an issue!

The first error occurs because you didn't add [`FFmpeg`](https://ffmpeg.org/) executable to your PATH variable. Also, folder names are now formatted as well (forbidden characters are replaced by a space), per c124c615aa79e756b08f5519cf3a9c3a2353dbec.

Closing this issue. If you still encounter some issues you can open it again or file a new one.
